package com.app.tweet.model;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBScalarAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConverted;

@DynamoDBTable(tableName = "Tweets")
public class Tweet {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute
	@NotBlank
	@Size(max = 144)
	private String tweet;
	@DynamoDBAttribute
	private Date date;
	
	@DynamoDBTypeConverted(converter = UserDetailConverter.class)
	@DynamoDBAttribute
	private TweetUserDetail user;

	@DynamoDBTypeConverted(converter = ReplyListConverter.class)
	@DynamoDBAttribute
	private List<ReplyTweet> reply;
	@DynamoDBTypeConverted(converter = UserDetailListConverter.class)
	@DynamoDBAttribute
	private List<TweetUserDetail> likes;
	
	@DynamoDBAttribute
	private String userId;	

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTweet() {
		return tweet;
	}

	public void setTweet(String tweet) {
		this.tweet = tweet;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public TweetUserDetail getUser() {
		return user;
	}

	public void setUser(TweetUserDetail user) {
		this.user = user;
	}

	public List<ReplyTweet> getReply() {
		return reply;
	}

	public void setReply(List<ReplyTweet> reply) {
		this.reply = reply;
	}

	public List<TweetUserDetail> getLikes() {
		return likes;
	}

	public void setLikes(List<TweetUserDetail> likes) {
		this.likes = likes;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}


}
